### ISSUE TITLE
Does not build in SBCL 2.0.9 - :initform/:type issue

### ISSUE THREAD

**Issue by quicklisp** [jmbr/cl-buchberger#7]
I get this: `Constant NIL conflicts with its asserted type VECTOR.`

Full log here: http://report.quicklisp.org/2020-09-30/failure-report/cl-buchberger.html#cl-buchberger

**Comment by jmbr** [comment]
Fixed by 4503216b4f2e3372daf4c9cca7b2e978cbc8256b.

Thank you.
